/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_litecore_C4Listener */

#ifndef _Included_com_couchbase_litecore_C4Listener
#define _Included_com_couchbase_litecore_C4Listener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_litecore_C4Listener
 * Method:    availableAPIs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_litecore_C4Listener_availableAPIs
  (JNIEnv *, jclass);

/*
 * Class:     com_couchbase_litecore_C4Listener
 * Method:    start
 * Signature: (IILjava/lang/String;ZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Listener_start
  (JNIEnv *, jclass, jint, jint, jstring, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_couchbase_litecore_C4Listener
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4Listener_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Listener
 * Method:    shareDB
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Listener_shareDB
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_couchbase_litecore_C4Listener
 * Method:    unshareDB
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Listener_unshareDB
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_litecore_C4Listener
 * Method:    uriNameFromPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_litecore_C4Listener_uriNameFromPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
