/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_litecore_C4Document */

#ifndef _Included_com_couchbase_litecore_C4Document
#define _Included_com_couchbase_litecore_C4Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_litecore_C4Document_getFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getDocID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_litecore_C4Document_getDocID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getRevID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_litecore_C4Document_getRevID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getSequence
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_getSequence
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getSelectedRevID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_litecore_C4Document_getSelectedRevID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getSelectedFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_litecore_C4Document_getSelectedFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getSelectedSequence
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_getSelectedSequence
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getSelectedBody
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_litecore_C4Document_getSelectedBody
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getSelectedBody2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_getSelectedBody2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    get
 * Signature: (JLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_get
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getBySequence
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_getBySequence
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    save
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4Document_save
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4Document_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    selectCurrentRevision
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_selectCurrentRevision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    loadRevisionBody
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4Document_loadRevisionBody
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    hasRevisionBody
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_hasRevisionBody
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    selectParentRevision
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_selectParentRevision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    selectNextRevision
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_selectNextRevision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    selectNextLeafRevision
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4Document_selectNextLeafRevision
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    selectFirstPossibleAncestorOf
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_selectFirstPossibleAncestorOf
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    selectNextPossibleAncestorOf
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_selectNextPossibleAncestorOf
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    selectCommonAncestorRevision
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_selectCommonAncestorRevision
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    purgeRevision
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_litecore_C4Document_purgeRevision
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    resolveConflict
 * Signature: (JLjava/lang/String;Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4Document_resolveConflict
  (JNIEnv *, jclass, jlong, jstring, jstring, jbyteArray, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    setExpiration
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4Document_setExpiration
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    getExpiration
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_getExpiration
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    put
 * Signature: (J[BLjava/lang/String;IZZ[Ljava/lang/String;ZII)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_put
  (JNIEnv *, jclass, jlong, jbyteArray, jstring, jint, jboolean, jboolean, jobjectArray, jboolean, jint, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    put2
 * Signature: (JJLjava/lang/String;IZZ[Ljava/lang/String;ZII)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_put2
  (JNIEnv *, jclass, jlong, jlong, jstring, jint, jboolean, jboolean, jobjectArray, jboolean, jint, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    create
 * Signature: (JLjava/lang/String;[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_create
  (JNIEnv *, jclass, jlong, jstring, jbyteArray, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    create2
 * Signature: (JLjava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_create2
  (JNIEnv *, jclass, jlong, jstring, jlong, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    update
 * Signature: (J[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_update
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    update2
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4Document_update2
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    dictContainsBlobs
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_litecore_C4Document_dictContainsBlobs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_litecore_C4Document
 * Method:    bodyAsJSON
 * Signature: (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_litecore_C4Document_bodyAsJSON
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
