/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_C4BlobReadStream */

#ifndef _Included_com_couchbase_lite_internal_C4BlobReadStream
#define _Included_com_couchbase_lite_internal_C4BlobReadStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_C4BlobReadStream
 * Method:    read
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_internal_C4BlobReadStream_read
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4BlobReadStream
 * Method:    getLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_C4BlobReadStream_getLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4BlobReadStream
 * Method:    seek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_C4BlobReadStream_seek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4BlobReadStream
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_C4BlobReadStream_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
