/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_litecore_C4BlobKey */

#ifndef _Included_com_couchbase_litecore_C4BlobKey
#define _Included_com_couchbase_litecore_C4BlobKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_litecore_C4BlobKey
 * Method:    fromString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4BlobKey_fromString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_couchbase_litecore_C4BlobKey
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_litecore_C4BlobKey_toString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_C4BlobKey
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4BlobKey_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
