/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_fleece_FLDict */

#ifndef _Included_com_couchbase_lite_internal_fleece_FLDict
#define _Included_com_couchbase_lite_internal_fleece_FLDict
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_fleece_FLDict
 * Method:    count
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_fleece_FLDict_count
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_fleece_FLDict
 * Method:    get
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_fleece_FLDict_get
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
