/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_C4Replicator */

#ifndef _Included_com_couchbase_lite_internal_C4Replicator
#define _Included_com_couchbase_lite_internal_C4Replicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    create
 * Signature: (JLjava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;JIILjava/lang/Object;ILjava/lang/Object;Lcom/couchbase/lite/internal/C4ReplicationFilter;Lcom/couchbase/lite/internal/C4ReplicationFilter;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_C4Replicator_create
  (JNIEnv *, jclass, jlong, jstring, jstring, jint, jstring, jstring, jlong, jint, jint, jobject, jint, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    createWithSocket
 * Signature: (JJIILjava/lang/Object;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_internal_C4Replicator_createWithSocket
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jobject, jbyteArray);

/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    free
 * Signature: (JLjava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_C4Replicator_free
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_C4Replicator_stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    getStatus
 * Signature: (J)Lcom/couchbase/lite/internal/C4ReplicatorStatus;
 */
JNIEXPORT jobject JNICALL Java_com_couchbase_lite_internal_C4Replicator_getStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    getResponseHeaders
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_internal_C4Replicator_getResponseHeaders
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    mayBeTransient
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_internal_C4Replicator_mayBeTransient
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_couchbase_lite_internal_C4Replicator
 * Method:    mayBeNetworkDependent
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_internal_C4Replicator_mayBeNetworkDependent
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
