/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_litecore_C4Key */

#ifndef _Included_com_couchbase_litecore_C4Key
#define _Included_com_couchbase_litecore_C4Key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_litecore_C4Key
 * Method:    pbkdf2
 * Signature: (Ljava/lang/String;[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_litecore_C4Key_pbkdf2
  (JNIEnv *, jclass, jstring, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
