/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_C4Base */

#ifndef _Included_com_couchbase_lite_internal_C4Base
#define _Included_com_couchbase_lite_internal_C4Base
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_C4Base
 * Method:    getMessage
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_internal_C4Base_getMessage
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_couchbase_lite_internal_C4Base
 * Method:    setTempDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_C4Base_setTempDir
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
