/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_C4RawDocument */

#ifndef _Included_com_couchbase_lite_internal_C4RawDocument
#define _Included_com_couchbase_lite_internal_C4RawDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_C4RawDocument
 * Method:    key
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_internal_C4RawDocument_key
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4RawDocument
 * Method:    meta
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_internal_C4RawDocument_meta
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_internal_C4RawDocument
 * Method:    body
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_internal_C4RawDocument_body
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
