/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_litecore_C4DocumentObserver */

#ifndef _Included_com_couchbase_litecore_C4DocumentObserver
#define _Included_com_couchbase_litecore_C4DocumentObserver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_litecore_C4DocumentObserver
 * Method:    create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_C4DocumentObserver_create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_litecore_C4DocumentObserver
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_C4DocumentObserver_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
