/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_litecore_fleece_FLSliceResult */

#ifndef _Included_com_couchbase_litecore_fleece_FLSliceResult
#define _Included_com_couchbase_litecore_fleece_FLSliceResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_litecore_fleece_FLSliceResult
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_fleece_FLSliceResult_init
  (JNIEnv *, jclass);

/*
 * Class:     com_couchbase_litecore_fleece_FLSliceResult
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_litecore_fleece_FLSliceResult_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_fleece_FLSliceResult
 * Method:    getBuf
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_litecore_fleece_FLSliceResult_getBuf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_litecore_fleece_FLSliceResult
 * Method:    getSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_litecore_fleece_FLSliceResult_getSize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
