/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_C4 */

#ifndef _Included_com_couchbase_lite_internal_C4
#define _Included_com_couchbase_lite_internal_C4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_C4
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_internal_C4_setenv
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_couchbase_lite_internal_C4
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_internal_C4_getenv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_couchbase_lite_internal_C4
 * Method:    getBuildInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_internal_C4_getBuildInfo
  (JNIEnv *, jclass);

/*
 * Class:     com_couchbase_lite_internal_C4
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_internal_C4_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
