/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_touchdb_TDCollateJSON */

#ifndef _Included_com_couchbase_touchdb_TDCollateJSON
#define _Included_com_couchbase_touchdb_TDCollateJSON
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_touchdb_TDCollateJSON
 * Method:    nativeRegisterCustomCollators
 * Signature: (Landroid/database/sqlite/SQLiteDatabase;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_touchdb_TDCollateJSON_nativeRegisterCustomCollators
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_couchbase_touchdb_TDCollateJSON
 * Method:    testCollateJSON
 * Signature: (IILjava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_touchdb_TDCollateJSON_testCollateJSON
  (JNIEnv *, jclass, jint, jint, jstring, jint, jstring);

/*
 * Class:     com_couchbase_touchdb_TDCollateJSON
 * Method:    testEscape
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_com_couchbase_touchdb_TDCollateJSON_testEscape
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_couchbase_touchdb_TDCollateJSON
 * Method:    testDigitToInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_touchdb_TDCollateJSON_testDigitToInt
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
