/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_android_SQLiteRevCollator */

#ifndef _Included_com_couchbase_lite_android_SQLiteRevCollator
#define _Included_com_couchbase_lite_android_SQLiteRevCollator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_android_SQLiteRevCollator
 * Method:    nativeRegister
 * Signature: (Ljava/lang/Object;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_android_SQLiteRevCollator_nativeRegister
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     com_couchbase_lite_android_SQLiteRevCollator
 * Method:    testCollateRevIds
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_android_SQLiteRevCollator_testCollateRevIds
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
