/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_touchdb_RevCollator */

#ifndef _Included_com_couchbase_touchdb_RevCollator
#define _Included_com_couchbase_touchdb_RevCollator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_touchdb_RevCollator
 * Method:    nativeRegister
 * Signature: (Landroid/database/sqlite/SQLiteDatabase;I)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_touchdb_RevCollator_nativeRegister
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_couchbase_touchdb_RevCollator
 * Method:    testCollateRevIds
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_touchdb_RevCollator_testCollateRevIds
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
